### ISSUE TITLE
.bat ?

### ISSUE THREAD

**Issue by Rexator3000** [moovida/remarkable-hyutilities#1]
I can't see batch file anywhere

**Comment by moovida** [comment]
Outch, I packaged it wrong. I just placed the jar. 
You have to download the previous release for the bat, or create a new one with:
```
@echo off
START /B java -jar remarkable_hyutilities_v1.1.jar
```
Inside it.

Also doubleclick on the jar might work.

**Comment by sfkiesling** [comment]
Could you update the README to reflect this? 
Thanks!

**Comment by moovida** [comment]
Sorry to have taken that long. This release has also an exe for windows.
https://github.com/moovida/remarkable-hyutilities/releases/download/v1.2/remarkable_hyutilities_v1.2.zip
