### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Eeems** [moovida/remarkable-hyutilities#15]
There doesn't seem to be a license, so it's not clear what users can and cannot do with the codebase.

**Comment by moovida** [comment]
License is refenrences in the section: https://github.com/moovida/remarkable-hyutilities#warning

**Comment by moovida** [comment]
And license file added.

**Comment by Eeems** [comment]
> 
> 
> License is referenced in the section: https://github.com/moovida/remarkable-hyutilities#warning

Apologies, I didn't notice that while skimming through the repository. Thanks for adding the license file to make it clearer :)
