### ISSUE TITLE
No backup button

### ISSUE THREAD

**Issue by msauers** [moovida/remarkable-hyutilities#3]
It running and I'm connected to my device. But there's not backup button as in the documentation screenshots.
![javaw_2018-09-20_08-48-54](https://user-images.githubusercontent.com/491936/45822890-135f1880-bcb2-11e8-9c9f-788c5362ac32.png)

**Comment by msauers** [comment]
1.1 but surprisingly it's there now. So I guess this one solved itself. Thanks,

**Comment by moovida** [comment]
Happy to hear that. I will sure have to improve some error messaging and check the remarkable version also.
Thanks
