### ISSUE TITLE
Basefolder not applied

### ISSUE THREAD

**Issue by pcornelissen** [moovida/remarkable-hyutilities#4]
I have downloaded the most recent jar abd started it with java 11.
I can enter hist, username and password, but when I select a directory (that contains the required 3 directories) it's not shown in the basefolder field and I canÄt up-/download anything from the device.

Fetching of the remote files list works though.

![bildschirmfoto vom 2018-11-30 11-15-28](https://user-images.githubusercontent.com/1177440/49283152-4af7f700-f491-11e8-9711-8db2c651b0f6.png)

**Comment by moovida** [comment]
Hi @pcornelissen , thanks for the report. Do you see errors in the console if you launch it from commandline?
I didn't try it with java 11, but since many things changed in there, it might be the problem.

**Comment by Tridens92** [comment]
I had a similar problem.  However, I selected the Basefolder, and then closed the app.  When I opened the app again, the Basefolder field was successfully populated, and upload and download worked fine.
