### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by unknwovl** [moovida/remarkable-hyutilities#5]
Dear Moovida, 

Thank you for developing Hyutilities. However I have newbie / basic issues trying to connect as I get "ERROR auth fail".
I plugged it using USB to the Mac with the "USB web interface" on. The USB web interface works.

I see in your Readme guide 2 elements that I don't understand:
- the IP address I have entered is 10.11.99.1 as indicated in the About section. Is it supposed to be connected via USB? or should I connect it via wifi? If so, how could I get the IP address?
- when you type in the password, the tablet would let me choose only 4-digits code whereas your readme scrrenshot shows more than 4 digits. What did I not understand? What code should I type?

Thanks for your reply and looking forward to using Hyutilities
(and sorry for the newbie questions).

Best regards,

Vincent

**Comment by moovida** [comment]
Hi Vincent, I added a small addition to the readme that should answer your question.

Have a look at the FAQ section: https://github.com/moovida/remarkable-hyutilities/blob/master/README.md

Let me know if it works for you.

**Comment by unknwovl** [comment]
Hi @moovida Thank you very much for your quick reply and help. It is much clearer now. I am indeed able to find my Wifi IP address now. 
However, unless the required password is not the 4-digit passcode to lock the tablet, everything I entered is fine, but I still get the "auth fail" Error.
To be noted, I do not a rM cloud account set up (for confidentiality reasons). Maybe that'll be the issue?

Thanks again,

Vincent

**Comment by moovida** [comment]
So you are inserting now the strange password proposed by the remarkable, right? 
Did you try both ip addresses proposed? Maybe it is not able to connect?

No, an account should not be necessary, we are really logging into the remarkable as a pc. Would you mind sending a screenshot? The password will be blacked anyways, so it should not be a problem.

**Comment by unknwovl** [comment]
![usbIP](https://user-images.githubusercontent.com/48795295/54876962-b1c26700-4e18-11e9-9ead-09ffd530cfcc.png)
![wifiIP](https://user-images.githubusercontent.com/48795295/54876963-b1c26700-4e18-11e9-94b7-7852e1bcc7ac.png)

I tired both IP and connected (of course on the same WiFi network). It's clear the good IP is the one you helped me to find in your updated readme.

Can you give more details about the "strange password" you are mentioning. Again I can only think of the 4-digit passcode used to lock the device and your screenshot shows  a 10-digit password...

Thanks again for your time @moovida

**Comment by moovida** [comment]
Hi @unknwovl , the second ip address is the right one, but you get an authentication error, because you are using the pin to access the device and not the password supplied for the ssh connection.

I added to the FAQ section a screenshot that shows where to find the passsword. Can you have a look and see if that one is clear? That is teh password you will need to enter in the application. Good luck!

**Comment by unknwovl** [comment]
Thanks !!!! A lot !!
