### ISSUE TITLE
Templates not working with 1.8.0.4

### ISSUE THREAD

**Issue by stekman** [moovida/remarkable-hyutilities#6]
When uploading to 1.8.0.4 you get a dialog box with 

ERROR: null

template.json is updated, but I think the pngs fails to upload (unfortunately did not check before uploading them with scp as I thought nothing worked).

**Comment by moovida** [comment]
I just did the update to that version without any issue. Do you have any more information or error messages (from the console?)?

For me the first time it gave me a connection timeout, but then the second time it runs smooth. Did you try a second run?

**Comment by stekman** [comment]
filesize=16754, file=templates.json
scp: ambiguous target

**Comment by stekman** [comment]
Runtime Exception at line 118 in SshHelper, due to return value of 67 from the checkAck method.

localFile = "/Users/stekman/remarkable/templates/templates.json"
remoteFile = "/usr/share/remarkable/templates/templates.json"
command = "scp -p -t /usr/share/remarkable/templates/templates.json"

**Comment by stekman** [comment]
Template file is actually updated on remarkable. Each time getting duplicate entries.

**Comment by moovida** [comment]
Thanks for the fix. Closing this here.
