### ISSUE TITLE
v1.2 - Nothing happens when running start.exe on Windows 10

### ISSUE THREAD

**Issue by Tridens92** [moovida/remarkable-hyutilities#9]
Thanks for the update to v. 1.2.  However, according to the directions, all I should need to do is unzip, have Java installed, and run Start.exe on Windows 10.  When I do that, nothing happens at all, at least visually.  No window opens, no error message, no nothing.  Thanks for any help you can offer.

**Comment by moovida** [comment]
Thanks for the report. Are you able to run the start.exe from a terminal?
That should give an error message and give us some insight. I would be keen on solving this.

**Comment by Tridens92** [comment]
moovida,

Thanks for looking into this.  Unfortunately, starting from a command prompt offers no further indication of problem.  Here's a URL to a screenshot: https://www.dropbox.com/s/9q8c6gydqeohucd/2019-09-25_20h15_57.png?dl=0

Thanks for your continued work.

**Comment by moovida** [comment]
Hi @Tridens92 , thanks for testing. Could you try to run the **generic.bat** from the same terminal instead? That should tell us something more.

**Comment by pgoddard10** [comment]
Hi,

Also having the same issue. The start.exe program shows in Task Manager but nothing happens. I've run generic.bat through command prompt, see attached error describing the missing .jar file: Unable to access jarfile remarkable_hyutilities_v1.2.jar

Running start.exe through command prompt just returns to a new line, no error etc.

<img width="819" alt="run generic through cmd" src="https://user-images.githubusercontent.com/48760536/71320443-4a1e7280-24a3-11ea-9908-e0e96f23d9d5.png">

**Comment by moovida** [comment]
Just a check. Did you try to download it again and start over?
The error message tells me that it doesn't find the main jar file, which sounds like it is corrupted.

**Comment by pgoddard10** [comment]
Where is the .jar file stored? I can't see it in the repo or when I search via https://github.com/moovida/remarkable-hyutilities/find/master

**Comment by moovida** [comment]
It is inside the installation folder:
![image](https://user-images.githubusercontent.com/390250/71347243-38ec6900-256a-11ea-9a74-8ed64e80f452.png)

It is generated on deployment of the app. Your console has a message that tells that it can't access that file.

**Comment by pgoddard10** [comment]
Hi @moovida 

It seems that the file is not being generated. The file is not present in the GitHub repo and I've downloaded the contents three times with the same error each time.

**Comment by moovida** [comment]
Ahhhhhh, now I see, sorry, I didn't notice.
The repository itself is just the code for developers that want to contribute.

The ready to run software can be downloaded from the releases page: https://github.com/moovida/remarkable-hyutilities/releases

For example right now the latest release is: https://github.com/moovida/remarkable-hyutilities/releases/download/v1.3/remarkable_hyutilities_v1.3.zip

which is the zip you can see in the assets part.
That zip contains exactly what you are searching for.

**Comment by pgoddard10** [comment]
![face-palm_1f926](https://user-images.githubusercontent.com/48760536/71359193-7f01f680-2583-11ea-958f-8430a1500265.png)

Ha ha! I'm so sorry - the .jar is present from the download link and (once I updated Java), worked perfectly. Thank you!

If you were interested, running Java version 7 displays these symptoms:

start.exe shows in Task Manager but nothing happening. I can close that (through Task Manager) and try to open generic.bat through Command Prompt, and it's struggling with the .jar file again (see screenshot below)

<img width="674" alt="error" src="https://user-images.githubusercontent.com/48760536/71359398-35fe7200-2584-11ea-8dbe-4f2ceebc11cf.png">

and this one if I move to the root of my C: drive.

<img width="674" alt="error2" src="https://user-images.githubusercontent.com/48760536/71359453-562e3100-2584-11ea-8346-bb93bbd34150.png">

Thanks again for your help.
